SET IDENTITY_INSERT [dbo].[Teachers] ON
INSERT INTO [dbo].[Teachers] ([Id], [Name], [Description], [Subscribers], [Followers], [Image]) VALUES (1, N'Albert Flores', N'Dolor ipsum amet cursus quisque porta adipiscing. Lorem convallis malesuada sed maecenas. Ac dui at vitae mauris cursus in nullam porta sem. Quis pellentesque elementum ac bibendum. Nunc aliquam in tortor facilisis. Vulputate eget risus, metus phasellus. Pellentesque faucibus amet, eleifend diam quam condimentum convallis ultricies placerat. Duis habitasse placerat amet, odio pellentesque rhoncus, feugiat at. Eget pellentesque tristique felis magna fringilla.', N'500', N'150', N'AlbertFlores.jpg')
INSERT INTO [dbo].[Teachers] ([Id], [Name], [Description], [Subscribers], [Followers], [Image]) VALUES (2, N'Robert Fox', N'Expert in JavaScript and React development', N'600', N'200', N'RobertFox.jpg')
INSERT INTO [dbo].[Teachers] ([Id], [Name], [Description], [Subscribers], [Followers], [Image]) VALUES (3, N'Esther Howard', N'Experienced in Python programming and data analysis', N'700', N'250', N'EstherHoward.jpg')
INSERT INTO [dbo].[Teachers] ([Id], [Name], [Description], [Subscribers], [Followers], [Image]) VALUES (4, N'Ralph Edwards', N'Skilled in iOS app development with Swift', N'550', N'180', N'RalphEdwards.jpg')
INSERT INTO [dbo].[Teachers] ([Id], [Name], [Description], [Subscribers], [Followers], [Image]) VALUES (5, N'Jenny Wilson', N'Jenny Wilson is a passionate web developer with extensive experience and expertise in HTML and CSS. With over five years of experience in the field, Jenny has developed and designed a wide range of websites and interfaces, from simple web pages to complex web applications. By combining her deep knowledge of HTML and CSS, Jenny not only creates visually appealing and functional websites, but also ensures they are responsive, accessible, and optimized for performance.

Jenny is not only skilled in writing clean and structured code, but she also has an understanding of design principles and user experience, making her a versatile resource for any project requiring an elegant and efficient web presence.', N'800', N'300', N'JennyWilson.jpg')
INSERT INTO [dbo].[Teachers] ([Id], [Name], [Description], [Subscribers], [Followers], [Image]) VALUES (6, N'Marvin McKinney', N'Mixed Knowledge', N'150', N'300', N'MarvinMcKinney.jpg')
INSERT INTO [dbo].[Teachers] ([Id], [Name], [Description], [Subscribers], [Followers], [Image]) VALUES (7, N'Anonymus', N'We do not have a teacher for this course yet', N'0', N'0', N'Anonymus.png')
SET IDENTITY_INSERT [dbo].[Teachers] OFF
