SET IDENTITY_INSERT [dbo].[Teachers] ON
INSERT INTO [dbo].[Teachers] ([Id], [Name], [Description], [Subscribers], [Followers], [Image]) VALUES (1, N'Albert Flores', N'Dolor ipsum amet cursus quisque porta adipiscing. Lorem convallis malesuada sed maecenas. Ac dui at vitae mauris cursus in nullam porta sem. Quis pellentesque elementum ac bibendum. Nunc aliquam in tortor facilisis. Vulputate eget risus, metus phasellus. Pellentesque faucibus amet, eleifend diam quam condimentum convallis ultricies placerat. Duis habitasse placerat amet, odio pellentesque rhoncus, feugiat at. Eget pellentesque tristique felis magna fringilla.', N'500', N'150', N'AlbertFlores.jpg')
INSERT INTO [dbo].[Teachers] ([Id], [Name], [Description], [Subscribers], [Followers], [Image]) VALUES (2, N'Robert Fox', N'Expert in JavaScript and React development', N'600', N'200', N'RobertFox.jpg')
INSERT INTO [dbo].[Teachers] ([Id], [Name], [Description], [Subscribers], [Followers], [Image]) VALUES (3, N'Esther Howard', N'Experienced in Python programming and data analysis', N'700', N'250', N'EstherHoward.jpg')
INSERT INTO [dbo].[Teachers] ([Id], [Name], [Description], [Subscribers], [Followers], [Image]) VALUES (4, N'Ralph Edwards', N'Skilled in iOS app development with Swift', N'550', N'180', N'RalphEdwards.jpg')
INSERT INTO [dbo].[Teachers] ([Id], [Name], [Description], [Subscribers], [Followers], [Image]) VALUES (5, N'Jenny Wilson', N'Jenny Wilson är en passionerad webbutvecklare med omfattande erfarenhet och expertis inom HTML och CSS. Med över fem års erfarenhet inom området har Jenny utvecklat och designat ett brett utbud av webbplatser och gränssnitt, från enkla webbsidor till komplexa webbapplikationer.

Genom att kombinera sina djupa kunskaper inom HTML och CSS skapar Jenny inte bara visuellt tilltalande och funktionella webbplatser, utan säkerställer också att de är responsiva, tillgängliga och optimerade för prestanda.

Jenny är inte bara skicklig inom att skriva ren och strukturerad kod, hon har också en förståelse för designprinciper och användarupplevelse, vilket gör henne till en mångsidig resurs för alla projekt som kräver en elegant och effektiv webbpresens.', N'800', N'300', N'JennyWilson.jpg')
INSERT INTO [dbo].[Teachers] ([Id], [Name], [Description], [Subscribers], [Followers], [Image]) VALUES (6, N'Marvin McKinney', N'Mixed Knowledge', N'150', N'300', N'MarvinMcKinney.jpg')
SET IDENTITY_INSERT [dbo].[Teachers] OFF
